image: Visual Studio 2019

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true
branches:
  only:
    - master
    - dev
    - release

init:
  - git config --global core.autocrlf true
install:
  - ps: $env:BuildNumber= $env:APPVEYOR_BUILD_NUMBER
  - ps: $env:DOTNET_SKIP_FIRST_TIME_EXPERIENCE = true
  - ps: $env:NUGET_XMLDOC_MODE = "skip"
  - ps: $env:DOTNET_CLI_TELEMETRY_OPTOUT = 1
  - ps: $IsReleaseBranch = ($env:APPVEYOR_REPO_BRANCH -eq "master" -Or $env:APPVEYOR_REPO_BRANCH -eq "release")
build_script:
  # Ensure we are not using the myget feed for dependencies
  - dotnet --version
  - dotnet pack Sandwych.SmartConfig.sln -c Release
test_script:
  - dotnet test .\test\Sandwych.SmartConfig.Test\Sandwych.SmartConfig.Test.csproj -c Release
artifacts:
  - path: 'src\**\*.nupkg'
deploy:  
  - provider: NuGet
    on:
      branch: release
    server: https://www.nuget.org/api/v2/package
    api_key:
      secure: 76dWrCJVCm1+cBO+WmjmZIvpAw7sf416N/UJWHMbshmC7BOBabuC4Mm6PP2MWdGk
    skip_symbols: true
    artifact: /.*\.nupkg/  
  - provider: NuGet
    on:
      branch: master
    server: https://www.nuget.org/api/v2/package
    api_key:
      secure: 76dWrCJVCm1+cBO+WmjmZIvpAw7sf416N/UJWHMbshmC7BOBabuC4Mm6PP2MWdGk
    skip_symbols: true
    artifact: /.*\.nupkg/
